### ISSUE TITLE
 TypeError: device.defaultQueue.copyImageBitmapToTexture is not a function

### ISSUE THREAD

**Issue by thisisreza** [Twinklebear/webgpu-experiments#2]
I'm trying to open demos on Firefox Nightly but I got the following errors 

`Uncaught (in promise) TypeError: device.defaultQueue.copyImageBitmapToTexture is not a function
    uploadGLBModel https://www.willusher.io/webgpu-experiments/js/glb_import.js:628
    glbFile https://www.willusher.io/webgpu-experiments/js/glb_viewer.js:16
    promise callback*glbFile< https://www.willusher.io/webgpu-experiments/js/glb_viewer.js:16
    promise callback* https://www.willusher.io/webgpu-experiments/js/glb_viewer.js:16
    async* https://www.willusher.io/webgpu-experiments/js/glb_viewer.js:202
`

**Comment by Twinklebear** [comment]
Hi @thisisreza , the last time I tried this in Firefox Nightly they hadn't implemented the `copyImageBitmapToTexture` APIs yet and so it won't work in Firefox for now. In my own testing it seems like Chrome Canary is the furthest along on the WebGPU API implementation, so that's what I've been using for development.
